version: '2.2'

services:
  mongo:
    container_name: "kevin-mongo-docker-compose-deploy"
    ports:
      - "8020:27017"
    image: "mongo:latest"
    restart: always
  spring-boot:
    container_name: "kevin-spring-boot-docker-compose-deploy"
    ports:
      - "8021:8080"
    image: spring-boot-docker-github:latest
    restart: always