version: '2.2'

services:
  mongo:
    container_name: "kevin-geg-mongo-deploy"
    ports:
      - "8030:27017"
    image: "mongo:latest"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootrootroot
    restart: always
  spring-boot:
    container_name: "kevin-geg-server-deploy"
    ports:
      - "8031:8080"
    image: kevin-geg-server:latest
    restart: always